version: "3.7"
services:
  fpm:
    container_name: fpm
    build:
      context: .
      args:
        PHP_VERSION: 7.4-fpm-alpine
        COMPOSER_VERSION: latest
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./docker/workspace/.zshrc:/root/.zshrc

  mariadb:
    image: mariadb:10.4.11-bionic
    environment:
      MYSQL_ROOT_PASSWORD: sf
      MYSQL_DATABASE: sf
      MYSQL_USER: sf
      MYSQL_PASSWORD: sf
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    container_name: nginx
    image: nginx:1.16-alpine
    depends_on:
      - fpm
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    ports:
      - 8081:80

volumes:
  mysql_data:
    driver: local
